config/routes.rb
Prelang::Application.routes.draw do
  get "landings/index"
  resources :parents

  resources :children

  resources :attendances

  resources :schedules

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :child
end

app/models/child.rb
class Child < ActiveRecord::Base
  belongs_to :parent
  has_many :attendances
  has_and_belongs_to_many :schedules
end

app/models/parent.rb
class Parent < ActiveRecord::Base
  has_many :children
  validates_formatting_of :zipcode, using: :us_zip
  validates_formatting_of :phone, using: :us_phone
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  has_and_belongs_to_many :children
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  #->Prelang (user_login/devise)
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    # The User was found in our database
    return user if user

    # The User was not found and we need to create them
    User.create(name:     auth.extra.raw_info.name,
                provider: auth.provider,
                uid:      auth.uid,
                email:    auth.info.email,
                password: Devise.friendly_token[0,20])
  end


  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  #->Prelang (user_login:devise)
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up)        { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in)        { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end


  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/attendances_controller.rb
class AttendancesController < InheritedResources::Base
end

app/controllers/children_controller.rb
class ChildrenController < InheritedResources::Base
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
  end
end

app/controllers/parents_controller.rb
class ParentsController < InheritedResources::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < InheritedResources::Base
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include ApplicationHelper

  def facebook

    # Attempt to find the User
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication # This will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      #session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def passthru
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/attendances/_form.html.erb
<%= form_for @attendance, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :date, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :date, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :time_in, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :time_in, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :time_out, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :time_out, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  attendances_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<%- model_class = Attendance -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Attendance %></h1>
</div>
<%= render :partial => 'form' %>

app/views/attendances/index.html.erb
<%- model_class = Attendance -%>
<div class="page-header">
  <h1><%=t '.title', :default => Attendance %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:time_in) %></th>
      <th><%= model_class.human_attribute_name(:time_out) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @attendances.each do |attendance| %>
      <tr>
        <td><%= attendance.id %></td>
        <td><%= attendance.date %></td>
        <td><%= attendance.time_in %></td>
        <td><%= attendance.time_out %></td>
        <td><%=l attendance.created_at, format: :long %></td>
        <td>
          <%= link_to attendance_path(attendance), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to attendance_path(attendance), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_attendance_path,
            :class => 'btn btn-primary' %>

app/views/attendances/new.html.erb
<%- model_class = Attendance -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Attendance %></h1>
</div>
<%= render :partial => 'form' %>

app/views/attendances/show.html.erb
<%- model_class = Attendance -%>
<div class="page-header">
  <h1><%=t '.title', :default => Attendance %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:date) %></dt>
      <dd><pre class="prettyprint"><%= @attendance.date %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:time_in) %></dt>
      <dd><pre class="prettyprint"><%= @attendance.time_in %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:time_out) %></dt>
      <dd><pre class="prettyprint"><%= @attendance.time_out %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              attendances_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_attendance_path(@attendance), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              attendance_path(@attendance),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/children/_form.html.erb
<%= form_for @child, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :first_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :first_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :last_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :birthday, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :birthday, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :gender, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :gender, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  children_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/children/edit.html.erb
<%- model_class = Child -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Child %></h1>
</div>
<%= render :partial => 'form' %>

app/views/children/index.html.erb
<%- model_class = Child -%>
<div class="page-header">
  <h1><%=t '.title', :default => Child %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:birthday) %></th>
      <th><%= model_class.human_attribute_name(:gender) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @children.each do |child| %>
      <tr>
        <td><%= child.id %></td>
        <td><%= child.first_name %></td>
        <td><%= child.last_name %></td>
        <td><%= child.birthday %></td>
        <td><%= child.gender %></td>
        <td><%=l child.created_at, format: :long %></td>
        <td>
          <%= link_to child_path(child), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to child_path(child), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_child_path,
            :class => 'btn btn-primary' %>

app/views/children/new.html.erb
<%- model_class = Child -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Child %></h1>
</div>
<%= render :partial => 'form' %>

app/views/children/show.html.erb
<%- model_class = Child -%>
<div class="page-header">
  <h1><%=t '.title', :default => Child %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:first_name) %></dt>
      <dd><pre class="prettyprint"><%= @child.first_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:last_name) %></dt>
      <dd><pre class="prettyprint"><%= @child.last_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:birthday) %></dt>
      <dd><pre class="prettyprint"><%= @child.birthday %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:gender) %></dt>
      <dd><pre class="prettyprint"><%= @child.gender %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              children_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_child_path(@child), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              child_path(@child),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/landings/index.html.erb
<h1>Landings#index</h1>
<p>Find me in app/views/landings/index.html.erb</p>

app/views/parents/_form.html.erb
<%= form_for @parent, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :first_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :first_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :last_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :case_number, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :case_number, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :address, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :city, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :city, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :state, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :state, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :zipcode, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :zipcode, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :email, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :phone, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  parents_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/parents/edit.html.erb
<%- model_class = Parent -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Parent %></h1>
</div>
<%= render :partial => 'form' %>

app/views/parents/index.html.erb
<%- model_class = Parent -%>
<div class="page-header">
  <h1><%=t '.title', :default => Parent %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:case_number) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:zipcode) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @parents.each do |parent| %>
      <tr>
        <td><%= parent.id %></td>
        <td><%= parent.first_name %></td>
        <td><%= parent.last_name %></td>
        <td><%= parent.case_number %></td>
        <td><%= parent.address %></td>
        <td><%= parent.city %></td>
        <td><%= parent.state %></td>
        <td><%= parent.zipcode %></td>
        <td><%= parent.email %></td>
        <td><%= parent.phone %></td>
        <td><%=l parent.created_at, format: :long %></td>
        <td>
          <%= link_to parent_path(parent), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to parent_path(parent), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_parent_path,
            :class => 'btn btn-primary' %>

app/views/parents/new.html.erb
<%- model_class = Parent -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Parent %></h1>
</div>
<%= render :partial => 'form' %>

app/views/parents/show.html.erb
<%- model_class = Parent -%>
<div class="page-header">
  <h1><%=t '.title', :default => Parent %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:first_name) %></dt>
      <dd><pre class="prettyprint"><%= @parent.first_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:last_name) %></dt>
      <dd><pre class="prettyprint"><%= @parent.last_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:case_number) %></dt>
      <dd><pre class="prettyprint"><%= @parent.case_number %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:address) %></dt>
      <dd><pre class="prettyprint"><%= @parent.address %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:city) %></dt>
      <dd><pre class="prettyprint"><%= @parent.city %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:state) %></dt>
      <dd><pre class="prettyprint"><%= @parent.state %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:zipcode) %></dt>
      <dd><pre class="prettyprint"><%= @parent.zipcode %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:email) %></dt>
      <dd><pre class="prettyprint"><%= @parent.email %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:phone) %></dt>
      <dd><pre class="prettyprint"><%= @parent.phone %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              parents_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_parent_path(@parent), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              parent_path(@parent),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/schedules/_form.html.erb
<%= form_for @schedule, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  schedules_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<%- model_class = Schedule -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Schedule %></h1>
</div>
<%= render :partial => 'form' %>

app/views/schedules/index.html.erb
<%- model_class = Schedule -%>
<div class="page-header">
  <h1><%=t '.title', :default => Schedule %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.id %></td>
        <td><%= schedule.name %></td>
        <td><%=l schedule.created_at, format: :long %></td>
        <td>
          <%= link_to schedule_path(schedule), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to schedule_path(schedule), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_schedule_path,
            :class => 'btn btn-primary' %>

app/views/schedules/new.html.erb
<%- model_class = Schedule -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Schedule %></h1>
</div>
<%= render :partial => 'form' %>

app/views/schedules/show.html.erb
<%- model_class = Schedule -%>
<div class="page-header">
  <h1><%=t '.title', :default => Schedule %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @schedule.name %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              schedules_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_schedule_path(@schedule), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              schedule_path(@schedule),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>